name = ""finance-radar""
compatibility_date = ""2026-06-15""

[build]
command = ""SKIP_TYPESCRIPT_CHECK=true npm run build""
output_directory = ""apps/web/.next""
root_directory = "".""

[build.environment]
NPM_FLAGS = ""--prefix ./apps/web""
NODE_VERSION = ""20""
NEXT_DISABLE_TSC = ""true""
